# Generated by Django 3.2.3 on 2021-05-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('finished_on', models.DateTimeField(blank=True, null=True)),
                ('license_plate', models.TextField()),
            ],
        ),
    ]
